import Header from './Header'
import Footer from './Footer'
import Heading from './Heading'
import Pagination from './Pagination'
import Tags from './Tags'
import Product from './Product'
import Navigator from './Navigator'
import Profile from './Profile'
import Order from './Order'
import Products from './Products'
import Categories from './Categories'
import ProfileTags from './ProfileTags'
import ConfirmBox from './ConfirmBox'
import Role from './Role'
import Modal from './Modal'

export { Header, Footer, Heading, Pagination, Tags, Product, Navigator, Profile, Order, Products, Categories, ProfileTags, ConfirmBox, Role, Modal }
